[2024-05-26T11:35:24.640+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:24.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:35:24.643+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:35:24.642+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:24.701+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:35:24.694+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:35:24.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:24.747+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.113 seconds
[2024-05-26T11:35:54.892+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:54.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:35:54.896+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:35:54.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:54.921+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:35:54.916+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:35:54.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:35:54.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.063 seconds
[2024-05-26T11:36:25.159+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:25.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:36:25.163+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:36:25.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:25.184+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:36:25.180+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:36:25.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:25.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.059 seconds
[2024-05-26T11:36:55.379+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:55.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:36:55.383+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:36:55.382+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:55.419+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:36:55.413+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:36:55.422+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:36:55.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.068 seconds
[2024-05-26T11:37:26.064+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:37:26.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:37:26.158+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:37:26.151+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:37:26.547+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:37:26.339+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:37:26.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:37:36.771+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/dag_processing/processor.py", line 622, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-05-26T11:40:02.822+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:40:02.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:40:02.873+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:40:02.851+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:08.440+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:08.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:43:08.890+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:43:08.641+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:29.688+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:29.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:43:29.693+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:43:29.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:29.740+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/example_dag.py:13 SyntaxWarning: invalid escape sequence '\K'
[2024-05-26T11:43:29.741+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/example_dag.py:22 SyntaxWarning: invalid escape sequence '\K'
[2024-05-26T11:43:29.796+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:43:29.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:43:29.801+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:43:29.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.202 seconds
[2024-05-26T11:44:00.111+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:00.113+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:44:00.119+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:44:00.115+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:00.181+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:44:00.170+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:44:00.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:00.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.112 seconds
[2024-05-26T11:44:23.315+0000] {processor.py:161} INFO - Started process (PID=254) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:23.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:44:23.320+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:44:23.320+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:23.343+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/example_dag.py:13 SyntaxWarning: invalid escape sequence '\K'
[2024-05-26T11:44:23.344+0000] {logging_mixin.py:188} WARNING - /opt/airflow/dags/example_dag.py:22 SyntaxWarning: invalid escape sequence '\K'
[2024-05-26T11:44:23.380+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:44:23.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:44:23.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:44:23.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.096 seconds
[2024-05-26T11:45:12.195+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:12.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:45:12.199+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:45:12.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:12.242+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:45:12.232+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:45:12.245+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:12.275+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.086 seconds
[2024-05-26T11:45:42.424+0000] {processor.py:161} INFO - Started process (PID=188) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:42.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:45:42.428+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:45:42.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:42.451+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:45:42.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:45:42.453+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:45:42.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.053 seconds
[2024-05-26T11:46:12.691+0000] {processor.py:161} INFO - Started process (PID=199) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T11:46:12.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T11:46:12.694+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:46:12.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T11:46:12.751+0000] {logging_mixin.py:188} INFO - [2024-05-26T11:46:12.744+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T11:46:12.753+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T11:46:12.770+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.085 seconds
[2024-05-26T12:05:30.592+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:05:30.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:05:30.597+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:05:30.596+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:05:30.684+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:05:30.673+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:05:30.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:05:30.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.130 seconds
[2024-05-26T12:06:01.555+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:01.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:06:01.558+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:06:01.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:01.595+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:06:01.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:06:01.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:01.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.071 seconds
[2024-05-26T12:06:31.901+0000] {processor.py:161} INFO - Started process (PID=211) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:31.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:06:31.903+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:06:31.903+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:31.929+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:06:31.925+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:06:31.930+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:06:31.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.053 seconds
[2024-05-26T12:07:02.240+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:02.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:07:02.244+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:07:02.244+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:02.308+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:07:02.297+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:07:02.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:02.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.102 seconds
[2024-05-26T12:07:32.634+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:32.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:07:32.640+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:07:32.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:32.687+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:07:32.679+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:07:32.690+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:07:32.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.081 seconds
[2024-05-26T12:08:02.976+0000] {processor.py:161} INFO - Started process (PID=261) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:02.977+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:08:02.979+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:08:02.979+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:03.014+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:08:03.005+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:08:03.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:03.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.073 seconds
[2024-05-26T12:08:33.337+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:33.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:08:33.341+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:08:33.340+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:33.373+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:08:33.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:08:33.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:08:33.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.078 seconds
[2024-05-26T12:09:03.674+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:03.675+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:09:03.677+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:09:03.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:03.699+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:09:03.696+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:09:03.702+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:03.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.060 seconds
[2024-05-26T12:09:33.986+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:33.987+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:09:33.988+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:09:33.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:34.011+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:09:34.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:09:34.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:09:34.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.048 seconds
[2024-05-26T12:10:04.282+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:04.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:10:04.285+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:10:04.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:04.326+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:10:04.317+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:10:04.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:04.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.071 seconds
[2024-05-26T12:10:34.675+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:34.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:10:34.679+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:10:34.678+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:34.704+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:10:34.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:10:34.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:10:34.723+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.053 seconds
[2024-05-26T12:11:04.810+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:04.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:11:04.814+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:11:04.814+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:04.849+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:11:04.845+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:11:04.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:04.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.064 seconds
[2024-05-26T12:11:35.146+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:35.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:11:35.149+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:11:35.148+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:35.172+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:11:35.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:11:35.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:11:35.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.051 seconds
[2024-05-26T12:12:05.456+0000] {processor.py:161} INFO - Started process (PID=397) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:05.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:12:05.458+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:12:05.458+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:05.482+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:12:05.476+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:12:05.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:05.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.054 seconds
[2024-05-26T12:12:35.772+0000] {processor.py:161} INFO - Started process (PID=414) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:35.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:12:35.775+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:12:35.775+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:35.804+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:12:35.800+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:12:35.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:12:35.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.064 seconds
[2024-05-26T12:13:06.086+0000] {processor.py:161} INFO - Started process (PID=431) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:06.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:13:06.088+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:13:06.088+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:06.112+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:13:06.105+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:13:06.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:06.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.050 seconds
[2024-05-26T12:13:36.342+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:36.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:13:36.345+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:13:36.345+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:36.369+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:13:36.365+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:13:36.370+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:13:36.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.050 seconds
[2024-05-26T12:14:06.638+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:06.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:14:06.641+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:14:06.640+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:06.663+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:14:06.660+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:14:06.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:06.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.056 seconds
[2024-05-26T12:14:36.917+0000] {processor.py:161} INFO - Started process (PID=482) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:36.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:14:36.919+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:14:36.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:36.937+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:14:36.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:14:36.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:14:36.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.054 seconds
[2024-05-26T12:15:07.206+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:07.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:15:07.209+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:15:07.209+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:07.231+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:15:07.228+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:15:07.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:07.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.058 seconds
[2024-05-26T12:15:37.369+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:37.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:15:37.372+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:15:37.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:37.413+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:15:37.407+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:15:37.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:15:37.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.073 seconds
[2024-05-26T12:16:07.855+0000] {processor.py:161} INFO - Started process (PID=533) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:07.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:16:07.861+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:16:07.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:07.933+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:16:07.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:16:07.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:07.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.140 seconds
[2024-05-26T12:16:38.505+0000] {processor.py:161} INFO - Started process (PID=550) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:38.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:16:38.515+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:16:38.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:38.590+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:16:38.576+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:16:38.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:16:38.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.143 seconds
[2024-05-26T12:17:08.984+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:08.986+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:17:08.990+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:17:08.990+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:09.040+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:17:09.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:17:09.043+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:09.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.102 seconds
[2024-05-26T12:17:39.341+0000] {processor.py:161} INFO - Started process (PID=584) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:39.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:17:39.345+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:17:39.344+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:39.370+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:17:39.367+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:17:39.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:17:39.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.053 seconds
[2024-05-26T12:18:09.630+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:09.632+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:18:09.637+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:18:09.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:09.681+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:18:09.674+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:18:09.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:09.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.082 seconds
[2024-05-26T12:18:40.036+0000] {processor.py:161} INFO - Started process (PID=618) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:40.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:18:40.043+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:18:40.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:40.101+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:18:40.093+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:18:40.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:18:40.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.118 seconds
[2024-05-26T12:19:10.290+0000] {processor.py:161} INFO - Started process (PID=635) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:10.292+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:19:10.295+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:19:10.295+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:10.341+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:19:10.334+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:19:10.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:10.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.094 seconds
[2024-05-26T12:19:40.699+0000] {processor.py:161} INFO - Started process (PID=652) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:40.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:19:40.702+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:19:40.702+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:40.724+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:19:40.721+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:19:40.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:19:40.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.057 seconds
[2024-05-26T12:20:11.012+0000] {processor.py:161} INFO - Started process (PID=669) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:11.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:20:11.015+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:20:11.014+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:11.038+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:20:11.033+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:20:11.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:11.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.061 seconds
[2024-05-26T12:20:41.426+0000] {processor.py:161} INFO - Started process (PID=687) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:41.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:20:41.429+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:20:41.429+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:41.454+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:20:41.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:20:41.455+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:20:41.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.051 seconds
[2024-05-26T12:21:11.755+0000] {processor.py:161} INFO - Started process (PID=704) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:11.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:21:11.758+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:21:11.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:11.780+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:21:11.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:21:11.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:11.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.051 seconds
[2024-05-26T12:21:42.044+0000] {processor.py:161} INFO - Started process (PID=721) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:42.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:21:42.049+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:21:42.049+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:42.084+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:21:42.078+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:21:42.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:21:42.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.072 seconds
[2024-05-26T12:22:12.364+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:12.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:22:12.368+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:22:12.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:12.400+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:22:12.395+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:22:12.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:12.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.063 seconds
[2024-05-26T12:22:42.567+0000] {processor.py:161} INFO - Started process (PID=749) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:42.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:22:42.571+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:22:42.571+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:42.615+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:22:42.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:22:42.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:22:42.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.076 seconds
[2024-05-26T12:23:12.898+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:12.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:23:12.901+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:23:12.901+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:12.923+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:23:12.919+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:23:12.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:12.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.050 seconds
[2024-05-26T12:23:43.283+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:43.284+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:23:43.287+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:23:43.287+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:43.335+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:23:43.327+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:23:43.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:23:43.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.095 seconds
[2024-05-26T12:24:13.492+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:13.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:24:13.497+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:24:13.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:13.590+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:24:13.559+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:24:13.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:13.633+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.146 seconds
[2024-05-26T12:24:43.918+0000] {processor.py:161} INFO - Started process (PID=817) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:43.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:24:43.921+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:24:43.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:43.963+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:24:43.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:24:43.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:24:43.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.074 seconds
[2024-05-26T12:25:14.236+0000] {processor.py:161} INFO - Started process (PID=834) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:14.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:25:14.238+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:25:14.238+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:14.262+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:25:14.259+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:25:14.264+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:14.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.052 seconds
[2024-05-26T12:25:44.617+0000] {processor.py:161} INFO - Started process (PID=851) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:44.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:25:44.620+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:25:44.620+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:44.643+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:25:44.639+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:25:44.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:25:44.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.048 seconds
[2024-05-26T12:26:14.928+0000] {processor.py:161} INFO - Started process (PID=868) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:14.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:26:14.930+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:26:14.930+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:14.964+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:26:14.958+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:26:14.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:14.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.065 seconds
[2024-05-26T12:26:45.228+0000] {processor.py:161} INFO - Started process (PID=885) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:45.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:26:45.230+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:26:45.230+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:45.259+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:26:45.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:26:45.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:26:45.278+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.056 seconds
[2024-05-26T12:27:15.527+0000] {processor.py:161} INFO - Started process (PID=903) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:15.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:27:15.529+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:27:15.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:15.552+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:27:15.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:27:15.554+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:15.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.054 seconds
[2024-05-26T12:27:45.879+0000] {processor.py:161} INFO - Started process (PID=920) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:45.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:27:45.882+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:27:45.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:45.904+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:27:45.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:27:45.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:27:45.923+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.050 seconds
[2024-05-26T12:28:16.197+0000] {processor.py:161} INFO - Started process (PID=937) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:16.198+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:28:16.201+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:28:16.200+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:16.229+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:28:16.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:28:16.230+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:16.248+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.056 seconds
[2024-05-26T12:28:46.535+0000] {processor.py:161} INFO - Started process (PID=954) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:46.536+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:28:46.538+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:28:46.537+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:46.569+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:28:46.563+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:28:46.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:28:46.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.070 seconds
[2024-05-26T12:29:16.866+0000] {processor.py:161} INFO - Started process (PID=971) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:16.867+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:29:16.869+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:29:16.868+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:16.899+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:29:16.893+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:29:16.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:16.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.060 seconds
[2024-05-26T12:29:47.182+0000] {processor.py:161} INFO - Started process (PID=988) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:47.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:29:47.184+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:29:47.184+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:47.208+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:29:47.204+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:29:47.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:29:47.235+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.058 seconds
[2024-05-26T12:30:17.492+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:17.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:30:17.496+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:30:17.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:17.550+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:30:17.542+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:30:17.553+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:17.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.095 seconds
[2024-05-26T12:30:48.002+0000] {processor.py:161} INFO - Started process (PID=1022) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:48.004+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:30:48.006+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:30:48.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:48.038+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:30:48.034+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:30:48.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:30:48.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.060 seconds
[2024-05-26T12:31:18.285+0000] {processor.py:161} INFO - Started process (PID=1039) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:18.286+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:31:18.288+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:31:18.288+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:18.321+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:31:18.316+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:31:18.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:18.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.061 seconds
[2024-05-26T12:31:48.602+0000] {processor.py:161} INFO - Started process (PID=1056) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:48.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:31:48.606+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:31:48.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:48.636+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:31:48.631+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:31:48.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:31:48.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.066 seconds
[2024-05-26T12:32:18.908+0000] {processor.py:161} INFO - Started process (PID=1073) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:18.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:32:18.911+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:32:18.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:18.937+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:32:18.932+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:32:18.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:18.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.065 seconds
[2024-05-26T12:32:49.237+0000] {processor.py:161} INFO - Started process (PID=1090) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:49.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:32:49.240+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:32:49.240+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:49.276+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:32:49.269+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:32:49.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:32:49.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.064 seconds
[2024-05-26T12:33:19.555+0000] {processor.py:161} INFO - Started process (PID=1107) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:19.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:33:19.559+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:33:19.558+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:19.593+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:33:19.588+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:33:19.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:19.613+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.063 seconds
[2024-05-26T12:33:49.802+0000] {processor.py:161} INFO - Started process (PID=1124) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:49.803+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:33:49.804+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:33:49.804+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:49.827+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:33:49.822+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:33:49.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:33:49.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.047 seconds
[2024-05-26T12:34:20.136+0000] {processor.py:161} INFO - Started process (PID=1141) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:20.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:34:20.140+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:34:20.139+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:20.180+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:34:20.174+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:34:20.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:20.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.079 seconds
[2024-05-26T12:34:50.445+0000] {processor.py:161} INFO - Started process (PID=1158) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:50.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:34:50.448+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:34:50.448+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:50.478+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:34:50.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:34:50.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:34:50.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.056 seconds
[2024-05-26T12:35:20.781+0000] {processor.py:161} INFO - Started process (PID=1181) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:20.782+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:35:20.784+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:35:20.784+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:20.822+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:35:20.816+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:35:20.825+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:20.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.069 seconds
[2024-05-26T12:35:51.086+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:51.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:35:51.090+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:35:51.090+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:51.128+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:35:51.122+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:35:51.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:35:51.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.068 seconds
[2024-05-26T12:36:21.428+0000] {processor.py:161} INFO - Started process (PID=1215) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:21.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:36:21.431+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:36:21.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:21.469+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:36:21.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:36:21.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:21.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.073 seconds
[2024-05-26T12:36:51.776+0000] {processor.py:161} INFO - Started process (PID=1232) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:51.777+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:36:51.779+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:36:51.779+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:51.806+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:36:51.801+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:36:51.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:36:51.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.064 seconds
[2024-05-26T12:37:22.105+0000] {processor.py:161} INFO - Started process (PID=1249) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:22.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:37:22.110+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:37:22.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:22.149+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:37:22.142+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:37:22.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:22.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.088 seconds
[2024-05-26T12:37:52.524+0000] {processor.py:161} INFO - Started process (PID=1266) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:52.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:37:52.530+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:37:52.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:52.578+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:37:52.569+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:37:52.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:37:52.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.107 seconds
[2024-05-26T12:38:23.027+0000] {processor.py:161} INFO - Started process (PID=1283) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:23.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:38:23.033+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:38:23.032+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:23.107+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:38:23.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:38:23.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:23.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.143 seconds
[2024-05-26T12:38:53.433+0000] {processor.py:161} INFO - Started process (PID=1300) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:53.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:38:53.438+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:38:53.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:53.515+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:38:53.500+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:38:53.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:38:53.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.135 seconds
[2024-05-26T12:39:24.022+0000] {processor.py:161} INFO - Started process (PID=1315) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:24.024+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:39:24.029+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:39:24.028+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:24.103+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:39:24.090+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:39:24.110+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:24.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.143 seconds
[2024-05-26T12:39:54.473+0000] {processor.py:161} INFO - Started process (PID=1328) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:54.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:39:54.478+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:39:54.477+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:54.513+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:39:54.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:39:54.524+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:39:54.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.080 seconds
[2024-05-26T12:40:24.847+0000] {processor.py:161} INFO - Started process (PID=1345) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:24.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:40:24.850+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:40:24.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:24.878+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:40:24.872+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:40:24.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:24.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.067 seconds
[2024-05-26T12:40:55.311+0000] {processor.py:161} INFO - Started process (PID=1362) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:55.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:40:55.315+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:40:55.315+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:55.373+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:40:55.361+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:40:55.375+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:40:55.396+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.090 seconds
[2024-05-26T12:41:25.685+0000] {processor.py:161} INFO - Started process (PID=1379) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:25.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:41:25.689+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:41:25.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:25.746+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:41:25.736+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:41:25.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:25.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.102 seconds
[2024-05-26T12:41:56.110+0000] {processor.py:161} INFO - Started process (PID=1396) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:56.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:41:56.114+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:41:56.113+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:56.155+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:41:56.148+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:41:56.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:41:56.183+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.080 seconds
[2024-05-26T12:42:26.495+0000] {processor.py:161} INFO - Started process (PID=1413) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:26.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:42:26.498+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:42:26.498+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:26.537+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:42:26.531+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:42:26.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:26.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.075 seconds
[2024-05-26T12:42:56.850+0000] {processor.py:161} INFO - Started process (PID=1430) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:56.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:42:56.852+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:42:56.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:56.887+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:42:56.883+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:42:56.890+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:42:56.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.067 seconds
[2024-05-26T12:43:27.207+0000] {processor.py:161} INFO - Started process (PID=1447) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:27.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:43:27.212+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:43:27.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:27.263+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:43:27.255+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:43:27.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:27.289+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.088 seconds
[2024-05-26T12:43:57.481+0000] {processor.py:161} INFO - Started process (PID=1464) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:57.483+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:43:57.488+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:43:57.488+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:57.550+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:43:57.540+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:43:57.555+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:43:57.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.126 seconds
[2024-05-26T12:44:28.049+0000] {processor.py:161} INFO - Started process (PID=1481) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:28.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:44:28.055+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:44:28.055+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:28.125+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:44:28.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:44:28.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:28.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.131 seconds
[2024-05-26T12:44:58.424+0000] {processor.py:161} INFO - Started process (PID=1498) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:58.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:44:58.428+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:44:58.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:58.483+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:44:58.473+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:44:58.487+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:44:58.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.099 seconds
[2024-05-26T12:45:28.654+0000] {processor.py:161} INFO - Started process (PID=1515) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:28.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:45:28.657+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:45:28.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:28.694+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:45:28.685+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:45:28.697+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:28.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.072 seconds
[2024-05-26T12:45:58.983+0000] {processor.py:161} INFO - Started process (PID=1532) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:58.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:45:58.987+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:45:58.987+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:59.012+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:45:59.007+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:45:59.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:45:59.044+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.065 seconds
[2024-05-26T12:46:29.359+0000] {processor.py:161} INFO - Started process (PID=1549) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:29.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:46:29.363+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:46:29.363+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:29.402+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:46:29.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:46:29.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:29.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.064 seconds
[2024-05-26T12:46:59.658+0000] {processor.py:161} INFO - Started process (PID=1566) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:59.659+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:46:59.664+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:46:59.664+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:59.736+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:46:59.724+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:46:59.740+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:46:59.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.131 seconds
[2024-05-26T12:47:30.144+0000] {processor.py:161} INFO - Started process (PID=1583) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:47:30.146+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:47:30.150+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:47:30.149+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:47:30.208+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:47:30.199+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:47:30.212+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:47:30.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.107 seconds
[2024-05-26T12:48:00.551+0000] {processor.py:161} INFO - Started process (PID=1600) to work on /opt/airflow/dags/example_dag.py
[2024-05-26T12:48:00.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/example_dag.py for tasks to queue
[2024-05-26T12:48:00.554+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:48:00.553+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/example_dag.py
[2024-05-26T12:48:00.594+0000] {logging_mixin.py:188} INFO - [2024-05-26T12:48:00.579+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/example_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/example_dag.py", line 4, in <module>
    from minio import Minio
ModuleNotFoundError: No module named 'minio'
[2024-05-26T12:48:00.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/example_dag.py
[2024-05-26T12:48:00.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/example_dag.py took 0.071 seconds
