[2024-06-02T14:03:25.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-02T14:03:25.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-02T14:03:24.057134+00:00 [queued]>
[2024-06-02T14:03:25.997+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-02T14:03:24.057134+00:00 [queued]>
[2024-06-02T14:03:25.999+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-06-02T14:03:26.019+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_files_to_cloud_storage_task> on 2024-06-02 14:03:24.057134+00:00
[2024-06-02T14:03:26.031+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_files_to_cloud_storage_dag', 'upload_files_to_cloud_storage_task', 'manual__2024-06-02T14:03:24.057134+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/input.py', '--cfg-path', '/tmp/tmpv5q2kw1l']
[2024-06-02T14:03:26.034+0000] {standard_task_runner.py:91} INFO - Job 116: Subtask upload_files_to_cloud_storage_task
[2024-06-02T14:03:26.036+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12066) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-02T14:03:26.037+0000] {standard_task_runner.py:63} INFO - Started process 12081 to run task
[2024-06-02T14:03:26.086+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_files_to_cloud_storage_dag.upload_files_to_cloud_storage_task manual__2024-06-02T14:03:24.057134+00:00 [running]> on host f69b53e362bb
[2024-06-02T14:03:26.194+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='upload_files_to_cloud_storage_dag' AIRFLOW_CTX_TASK_ID='upload_files_to_cloud_storage_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T14:03:24.057134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-02T14:03:24.057134+00:00'
[2024-06-02T14:03:26.196+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-02T14:03:26.235+0000] {base.py:84} INFO - Using connection ID '***s3' for task execution.
[2024-06-02T14:03:26.237+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='***s3', conn_type='aws') credentials retrieved from extra.
[2024-06-02T14:03:26.955+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-02T14:03:26.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-02T14:03:26.974+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=upload_files_to_cloud_storage_dag, task_id=upload_files_to_cloud_storage_task, run_id=manual__2024-06-02T14:03:24.057134+00:00, execution_date=20240602T140324, start_date=20240602T140325, end_date=20240602T140326
[2024-06-02T14:03:27.015+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-02T14:03:27.035+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-02T14:03:27.039+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
